### ISSUE TITLE
Reformatting dataset according to John's Hopkins CSSE dataset required

### ISSUE THREAD

**Issue by snoop2head** [KKodiac/Covid19_Stats#2]
[Johns Hopkins Timeseries data](https://github.com/CSSEGISandData/COVID-19/blob/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv) is mainly used to datascientists as a standard dataset. 
In future, I will reformat dataset into the same format as CSSE dataset.

**Comment by KKodiac** [comment]
That would be much appreciated! I'll be looking forward to hearing from you and look further into reformatting other datasets based on your contribution. Thank you again!!
